# Матаппарат для построения НС

*Нейронная сеть* - это последовательность геометрических преобразований в многомерном пространстве, реализованное в виде последовательности простых шагов.

### Скаляры (тензоры 0 ранга)

Скаляр - это тензор, содержащий единственное число.

In [2]:
import numpy as np
x = np.array(12)
x

array(12)

In [3]:
x.ndim # скалярный тензор имеет 0 осей

0

### Векторы (тензоры 1 ранга)

Вектор - это одномерный массив чисел.

In [4]:
x = np.array([12, 3, 6, 14])
x

array([12,  3,  6, 14])

In [5]:
x.ndim # Пятимерный вектор - имеет только одну ось и пять значений на этой оси

1

## Матрицы (тензоры 2 ранга)

Матрица имеет две оси (столбцы и строки), поэтому она - тензор второго порядка.

In [6]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])

In [7]:
x.ndim

2

Здесь **[5, 78, 2, 35, 0]** - первая строка,    
а **[5, 6, 7]** - первый столбец.

## Тензоры третьего и высших порядков

In [8]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])

In [9]:
x.ndim

3

Тензор - это:
1. Количество осей (ранг) - например, трехмерный тензор имеет три оси, а матрица - две;
2. Форма - матрица в примере выше имеет форму (3, 5), а трехмерный тензор имеет форму (3, 3, 5);    
3. Тип данных - тип данных, содержащийся в тензоре (float32, float64, uint8, редко char).

## Примеры тензоров с данными

*Векторные данные* - тензоры с формой (образцы, признаки);        
*Временные ряды* - трёхмерные тензоры с формой (образцы, метки времени, признаки);   
*Изображения* - четырёхмерные тензоры с формой (образцы, высота, ширина, цвет);
*Видео* - пятимерные тензоры с формой (образцы, кадры, высота, ширина, цвет) или с формой (образцы, кадры, цвет, высота, ширина)

***Пример 1:*** есть данные с информацией о людях.    
Для каждого человека указывается возраст, почтовый индекс и доход -> для 100000 человек можно сохранить двумерный тензор с формой (100000, 3)

***Пример 2:*** пакет со 128 чёрно-белыми изображениями, имеющими размер $256*256$, можно сохранить в тензоре с формой (128, 256, 256, 1), а пакет со 128 цветными изображениями - в тензоре с формой (128, 256, 256, 3).

<img src="images/1.png">

***Пример 3:*** 60-секундный видеоклип с разрешение $144*256$ и частотой 4 кадра в секунду будет состоять из 240 кадров. Для сохранения клипов потребуется тензор с формой (4, 240, 144, 256, 3). 

## Поэлементные операции
### Операция $relu$

In [10]:
import numpy as np


def naive_relu(x):
    """RELU: пробегаем по матрице и для каждого элемента выбираем 
    максимум между нулем и самим значением элемента"""
    
    assert len(x.shape) == 2  # убедиться, что x - двумерный вектор
    x = x.copy()  # исключить затирание исходного тензора
    print('Изначальный массив: \n', x)
    print('Форма: \n', x.shape)
    print('\n\n')
    
    # Мы пробегаем по строкам...
    for i in range(x.shape[0]):
        # ...и по столбцам
        for j in range(x.shape[1]):
            # Мы выбираем максимум из элемента матрица и нуля
            x[i, j] = max(x[i, j], 0)
    return x


x = np.array([[-5, 78, 2, 34, 0],
              [-6, 79, -3, -35, 1],
              [7, 80, -4, 36, 2]])

naive_relu(x)


Изначальный массив: 
 [[ -5  78   2  34   0]
 [ -6  79  -3 -35   1]
 [  7  80  -4  36   2]]
Форма: 
 (3, 5)





array([[ 0, 78,  2, 34,  0],
       [ 0, 79,  0,  0,  1],
       [ 7, 80,  0, 36,  2]])

### Операция сложения

In [11]:
def naive_add(x, y):
    """Поэлементное сложение тензоров"""
    
    assert len(x.shape)==2  # убедиться, что x и y - двумерные тензоры
    assert x.shape == y.shape
    x = x.copy()  # исключить затухание исходного тензора
    
    # Мы пробегаем по строкам...
    for i in range(x.shape[0]):
        # ...и по столбцам
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x


x = np.array([[-5, 78, 2, 34, 0],
              [-6, 79, -3, -35, 1],
              [7, 80, -4, 36, 2]])

y = np.array([[0, 12, 5, -17, -9],
              [-6, 79, -3, -35, 0],
              [7, 80, -4, 36, 2]])

z = x + y
print(z)

print('\n\n')

z = np.maximum(z, 0.)
print(z)


[[ -5  90   7  17  -9]
 [-12 158  -6 -70   1]
 [ 14 160  -8  72   4]]



[[  0.  90.   7.  17.   0.]
 [  0. 158.   0.   0.   1.]
 [ 14. 160.   0.  72.   4.]]


In [38]:
def naive_add_matrix_and_vector(x, y):
    """Поэлементное сложение вектора и матрицы (тензоров с разными формами)"""
    
    # Убедиться, что x - двумерный тензор Numpy
    assert len(x.shape) == 2.
    # Убедиться, что y - вектор Numpy
    assert len(y.shape) == 1.
    assert x.shape[1] == y.shape[0]
    
    x = x.copy() # Исключить затирание исходного тензора
    # Мы пробегаем по строкам...
    for i in range(x.shape[0]):
        # ...и по столбцам
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x


In [43]:
x = np.array([[-5, 78, 2, 34, 0],
              [-6, 79, -3, -35, 1],
              [7, 80, -4, 36, 2]])

y = np.array([0, 12, 5, -17, -9])

naive_add_matrix_and_vector(x, y)



array([[ -5,  90,   7,  17,  -9],
       [ -6,  91,   2, -52,  -8],
       [  7,  92,   1,  19,  -7]])

In [ ]:
def naive_vector_dot(x, y):
    """Обычное произведение векторов"""
    
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    z = 0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

## Скалярное произведение векторов

***Скалярное произведение*** - операция над двумя векторами, результатом которой является число, не зависящее от системы координат и характеризующее длины векторов-сомножителей и угол между ними. 
<img src="images/3.png" style="width: 175px;">

Замечание: скалярное произведение - не симметричная операция, то есть `dot(x, y) != dot(y, x)`

In [46]:
def naive_matrix_dot(x, y):
    """Скалярное произведение матриц"""
    
    # В операции могут участвовать только векторы с одинаковым количеством элементов
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0] # первое измерение x должно совпадать с нулевым измерением y
    
    z = np.zeros((x.shape[0], y.shape[1])) # Эта операция вернёт матрицу заданной формы с нулевыми элементами
    for i in range(x.shape[0]): # Обход строк в x...
        for j in range(y.shape[1]): # Обход столбцов в y...
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z



### Простейшая НС

In [5]:
from keras.datasets import mnist
from keras import models
from keras import layers

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Обучающие данные
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32') / 255

# Контрольные данные
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

# Сеть = цепочка двух слоёв Dense, каждый из которых применяет к входным данным несколько 
# простых операций с тензорами, вовлекающих весовые коэффициенты
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28, )))
network.add(layers.Dense(10, activation='softmax'))

# Этап компиляции
# Снижение потерь за счет стохастического градиентного спуска на небольших пакетах (=батчах)
network.compile (optimizer='rmsprop', # Тут указываются точные правила для применения SGD
                 loss='categorical_crossentropy', # Функция потерь, её сводим к минимуму
                                                  # Она используется в качестве сигнала для обучения весовых коэфф-в
                 metrics=['accuracy'])


# Сеть перебирает обучающие данные по 129 образцов и выполняет 5 итераций (=эпох). 
# Для каждого мини-пакета сеть вычисляет градиенты весов с учетом потерь в апкете и изменяет
# значения весов в соответствующем направлении
network.fit(train_images, train_labels, epochs=5, batch_size=128)