In [1]:
import torch

In [3]:
# Матрица 3 плоскости на 4 строчки на 3 столбика
torch.ones([3, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [6]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [10]:
x = x + 10

In [11]:
y = x ** 2

In [12]:
x/y

tensor([[0.0909, 0.0833, 0.0769, 0.0714],
        [0.0667, 0.0625, 0.0588, 0.0556],
        [0.0526, 0.0500, 0.0476, 0.0455]])

In [16]:
a = torch.ones([5, 4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])

tensor([1., 2., 3., 4.])

In [18]:
mask = b > 3
mask

tensor([[0, 0, 0, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [20]:
# Останутся только те элементы, которые больше трех
b[b>3] 

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
        18., 19., 20.])

In [28]:
# Пытаемся скопировать матрицу x в y и поменять в y одно из значений
# Здесь неправильное копирование: на объект в памяти x начинает ссылаться еще 
# и переменная y.

y = x
y[0,0] = 999
print(x)
print(y)

print('\n'*3,'-'*10)


x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
y = x.clone()
y[0,0] = 999
print(x)
print(y)

tensor([[999.,  12.,  13.,  14.],
        [ 15.,  16.,  17.,  18.],
        [ 19.,  20.,  21.,  22.]])
tensor([[999.,  12.,  13.,  14.],
        [ 15.,  16.,  17.,  18.],
        [ 19.,  20.,  21.,  22.]])



 ----------
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [29]:
x.dtype   # видим, что каждое число в x занимает 32 бита информации

# Можем перевести в int или float
x = x.int()
x = x.float() 
x = x.double()   # в double каждое число будет занимать 64 бита информации

torch.float32

In [32]:
import numpy as np

x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x = torch.from_numpy(x)  # перевод из numpy в tensor
print(x)

x = x.numpy()  # перевод из tensor в numpy
print(x)

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])
[[1 2 3 4]
 [4 3 2 1]]
